development:
  adapter: postgresql
  encoding: unicode
  database: sample_app_development
  host: localhost  
  pool: 5
  timeout: 5000
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: sample_app_test
  host: localhost  
  pool: 5
  timeout: 5000
  username: postgres
  password: password
